<a href="https://colab.research.google.com/github/Garvish47/Machine-Learning/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Q1

In [3]:
#a
a = np.array([1, 2, 3, 4, 5])

In [ ]:
print(np.flip(a))
print(a[::-1])

[5 4 3 2 1]
[5 4 3 2 1]


In [ ]:
#b
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print(array1)

print(array1.flatten())

print(np.ravel(array1))

[[1 2 3]
 [2 4 5]
 [1 2 3]]
[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


In [ ]:
#c
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

print(arr1 == arr2)

[[ True  True]
 [ True  True]]


In [ ]:
#d
x = np.array([1,2,3,4,5,1,2,1,1,1])
elements, counts = np.unique(x, return_counts = True)
print(elements, counts)

[1 2 3 4 5] [5 2 1 1 1]


In [ ]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
elements, counts = np.unique(y, return_counts = True)
print(elements, counts)

[1 2 3 4] [3 2 3 2]


In [5]:
#e
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
sum = gfg.sum()
print(sum)
print("\n")

row_wise_sum = gfg.sum(axis = 1)
print(row_wise_sum)
print("\n")

column_wise_sum = gfg.sum(axis = 0)
print(column_wise_sum)

45


[[14]
 [16]
 [15]]


[[20  9 16]]


In [15]:
#f
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
np.sum(np.diag(n_array))

np.int64(176)

In [17]:
eigenvalues, eigenvectors = np.linalg.eig(n_array)
print(eigenvalues)
print(eigenvectors)

[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


In [27]:
np.linalg.inv(n_array)

array([[ 0.02404141, -0.00911212, -0.00444671],
       [-0.01667882,  0.02966905,  0.0024785 ],
       [ 0.00631287, -0.01603732,  0.01217379]])

In [28]:
np.linalg.det(n_array)

np.float64(137180.0000000001)

In [2]:
#g
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
np.dot(p, q)

array([[16, 19],
       [26, 31]])

In [3]:
np.cov(p, q, rowvar = False)

array([[0.5, 0.5, 1. , 1. ],
       [0.5, 0.5, 1. , 1. ],
       [1. , 1. , 2. , 2. ],
       [1. , 1. , 2. , 2. ]])

In [4]:
#h
x = np.array([[2, 3, 4],
              [3, 2, 9]])

y = np.array([[1, 5, 0],
              [5, 10, 3]])

Q2-

In [2]:
#a
# Given array
array = np.array([[1, -2, 3], [-4, 5, -6]])

# 1. Element-wise absolute value
abs_array = np.abs(array)

# 2. Percentiles
flattened_array = array.flatten()
percentiles_flattened = np.percentile(flattened_array, [25, 50, 75])
percentiles_columns = np.percentile(array, [25, 50, 75], axis=0)
percentiles_rows = np.percentile(array, [25, 50, 75], axis=1)

# 3. Mean, Median, and Standard Deviation
mean_flattened = np.mean(flattened_array)
median_flattened = np.median(flattened_array)
std_flattened = np.std(flattened_array)

mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_columns = np.std(array, axis=0)

mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_rows = np.std(array, axis=1)

# Output the results
print("Absolute Value of the Array:")
print(abs_array)

print("\nPercentiles (Flattened Array):")
print(percentiles_flattened)

print("\nPercentiles (By Column):")
print(percentiles_columns)

print("\nPercentiles (By Row):")
print(percentiles_rows)

print("\nMean, Median, and Standard Deviation (Flattened Array):")
print(f"Mean: {mean_flattened}, Median: {median_flattened}, Std: {std_flattened}")

print("\nMean, Median, and Standard Deviation (By Column):")
print(f"Mean: {mean_columns}, Median: {median_columns}, Std: {std_columns}")

print("\nMean, Median, and Standard Deviation (By Row):")
print(f"Mean: {mean_rows}, Median: {median_rows}, Std: {std_rows}")

Absolute Value of the Array:
[[1 2 3]
 [4 5 6]]

Percentiles (Flattened Array):
[-3.5 -0.5  2.5]

Percentiles (By Column):
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]

Percentiles (By Row):
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]

Mean, Median, and Standard Deviation (Flattened Array):
Mean: -0.5, Median: -0.5, Std: 3.8622100754188224

Mean, Median, and Standard Deviation (By Column):
Mean: [-1.5  1.5 -1.5], Median: [-1.5  1.5 -1.5], Std: [2.5 3.5 4.5]

Mean, Median, and Standard Deviation (By Row):
Mean: [ 0.66666667 -1.66666667], Median: [ 1. -4.], Std: [2.05480467 4.78423336]


In [3]:
#b
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

# 1. Floor values
floor_values = np.floor(a)

# 2. Ceiling values
ceiling_values = np.ceil(a)

# 3. Truncated values
truncated_values = np.trunc(a)

# 4. Rounded values
rounded_values = np.round(a)

# Output the results
print("Floor values:", floor_values)
print("Ceiling values:", ceiling_values)
print("Truncated values:", truncated_values)
print("Rounded values:", rounded_values)

Floor values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values: [-2. -2. -0.  0.  2.  2.  3.]


Q3-

In [4]:
#a
array = np.array([10, 52, 62, 16, 16, 54, 453])

# 1. Sorted array
sorted_array = np.sort(array)

# 2. Indices of sorted array
indices_of_sorted_array = np.argsort(array)

# 3. 4 smallest elements
smallest_4_elements = sorted_array[:4]

# 4. 5 largest elements
largest_5_elements = sorted_array[-5:]

# Output the results
print("Sorted array:", sorted_array)
print("Indices of sorted array:", indices_of_sorted_array)
print("4 smallest elements:", smallest_4_elements)
print("5 largest elements:", largest_5_elements)


Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]


In [5]:
#b
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

# 1. Integer elements only
integer_elements = array[array == array.astype(int)]

# 2. Float elements only
float_elements = array[array != array.astype(int)]

# Output the results
print("Integer elements:", integer_elements)
print("Float elements:", float_elements)

Integer elements: [1. 2. 3. 2.]
Float elements: [1.2 2.2]


Q4-